esphome:
  name: ${devicename}
  friendly_name: ${friendlyname}

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Milfra MFA05F Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  include_internal: True
  log: True
  port: 80
  version: 3

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

tuya:
  time_id: homeassistant_time

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime Sensor
    entity_category: diagnostic
    internal: True

select:
  - platform: tuya
    name: Relay power loss restore
    enum_datapoint: 14
    optimistic: true
    options:
      0: "off"
      1: "on"
      2: "memory"
  - platform: tuya
    name: LED status
    enum_datapoint: 15
    optimistic: true
    options:
      0: "none"
      1: "relay"
      2: "motion"
  - platform: tuya
    name: cds_state
    enum_datapoint: 44
    optimistic: true
    options:
      0: "range"
      1: "on"
      2: "off"
    internal: True
  - platform: tuya
    name: cds_threshold
    enum_datapoint: 45
    optimistic: true
    options:
      0: "default"
      1: "now"
    internal: True
  # Enable/disable motion sensor
  - platform: tuya
    name: PIR status
    enum_datapoint: 47
    optimistic: true
    options:
      0: "on"
      1: "off"
    internal: True
  # Motion sensor sensitivity
  - platform: tuya
    name: PIR sensitivity
    enum_datapoint: 48
    optimistic: true
    options:
      0: "low"
      1: "middle"
      2: "high"
    internal: True

number:
  # Motion sensor delay
  - platform: tuya
    name: PIR Delay
    number_datapoint: 49
    min_value: 5
    max_value: 3600
    step: 1
    internal: True
  - platform: tuya
    name: Target time
    number_datapoint: 102
    min_value: 0
    max_value: 1440
    step: 1
    internal: True
  - platform: tuya
    name: Appointment time
    number_datapoint: 101
    min_value: 0
    max_value: 1440
    step: 1
    internal: True

switch:
  - platform: "tuya"
    name: ${friendlyname} switch
    switch_datapoint: 1
  - platform: "tuya"
    name: "cds_switch"
    switch_datapoint: 43
    internal: True
  - platform: "tuya"
    name: "switch_pir"
    switch_datapoint: 46
    internal: True

binary_sensor:
  #Status Binary Sensor exposes the node state (if it’s connected to via MQTT/native API) for Home Assistant.
  - platform: status
    name: "Connection Status"
    id: connection_status
    internal: True
    entity_category: diagnostic

button:
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: diagnostic
    internal: True

text_sensor:
  - platform: tuya
    name: "timer"
    sensor_datapoint: 103
    internal: True
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: "mdi:ip-outline"
      update_interval:  ${update_interval_wifi}
      internal: True
    ssid:
      name: "SSID"
      icon: "mdi:wifi-settings"
      update_interval:  ${update_interval_wifi}
      internal: True
    bssid:
      name: "BSSID"
      icon: "mdi:wifi-settings"
      update_interval:  ${update_interval_wifi}
      internal: True
    mac_address:
      name: "MAC"
      icon: "mdi:network-outline"
      internal: True
