esphome:
  name: ${devicename}
  friendly_name: ${friendlyname}

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Milfra MFA05F Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  include_internal: True
  log: true
  port: 80

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

tuya:
  time_id: homeassistant_time

time:
  - platform: homeassistant
    id: homeassistant_time

select:
  - platform: tuya
    name: Relay power loss restore
    enum_datapoint: 14
    optimistic: true
    options:
      0: "off"
      1: "on"
      2: "memory"
  - platform: tuya
    name: LED status
    enum_datapoint: 15
    optimistic: true
    options:
      0: "none"
      1: "relay"
      2: "motion"
  - platform: tuya
    name: cds_state
    enum_datapoint: 44
    optimistic: true
    options:
      0: "range"
      1: "on"
      2: "off"
  - platform: tuya
    name: cds_threshold
    enum_datapoint: 45
    optimistic: true
    options:
      0: "default"
      1: "now"
  - platform: tuya
    name: PIR status
    enum_datapoint: 47
    optimistic: true
    options:
      0: "on"
      1: "off"
  - platform: tuya
    name: PIR sensitivity
    enum_datapoint: 48
    optimistic: true
    options:
      0: "low"
      1: "middle"
      2: "high"
  - platform: tuya
    name: PIR Delay
    enum_datapoint: 49
    optimistic: true
    options:
      0: "low"
      1: "middle"
      2: "high"

number:
  - platform: tuya
    name: Target time
    number_datapoint: 102
    min_value: 0
    max_value: 1440
    step: 1
  - platform: tuya
    name: Appointment time
    number_datapoint: 101
    min_value: 0
    max_value: 1440
    step: 1
  - platform: tuya
    name: PIR Delay
    number_datapoint: 49
    min_value: 5
    max_value: 3600
    step: 1

switch:
  - platform: "tuya"
    name: ${longname} switch
    switch_datapoint: 1
  - platform: "tuya"
    name: "cds_switch"
    switch_datapoint: 43
  - platform: "tuya"
    name: "switch_pir"
    switch_datapoint: 46

text_sensor:
  - platform: tuya
    name: "timer"
    sensor_datapoint: 103
